kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  context: pytorch-demo
  dockerfile: ./Dockerfile

spec:
  operator: pytorch
  image: image
  command: "python3 src/main.py"

  tensorboard:
    enabled: true

  types:
    Master:
      count: 1
      resources:
        cpus: 8
        ramRatio: 4
        accelerators: # optional
          gpu:
            count: 1
            type: gpu
            product: nvidia-tesla-t4
    Worker:
      count: 1
      resources:
        cpus: 8
        ramRatio: 4
        accelerators: # optional
          gpu:
            count: 1
            type: gpu
            product: nvidia-tesla-t4

