# This manifest run the training with:
# - 2 container
# - 2 Tesla V100 32GB GPU per container (2*2=4GPUs)
#
# - mixed_precision fp16
# - batch_size 24
# - epochs 12
# - model: tinyllama
# Execution time: 25m11s.

kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  context: hugging-face-accelerate # hugging-face-accelerate folder
  dockerfile: ./Dockerfile

spec:
  operator: pytorch
  image: image
  command: "torchrun --nproc_per_node 2 main.py --mixed_precision fp16 --batch_size 24" # --nproc_per_node=={Number of GPUs}

  tensorboard:
    enabled: true

  types:
    Master:
      count: 1
      resources:
        cpus: 4
        ramRatio: 8 # 32GB
        accelerators: # optional
          gpu:
            count: 2
            type: gpu
            product: Tesla-V100-SXM3-32GB
    Worker:
      count: 1
      resources:
        cpus: 4
        ramRatio: 8 # 32GB
        accelerators: # optional
          gpu:
            count: 2
            type: gpu
            product: Tesla-V100-SXM3-32GB
