kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  dockerfile: ./build/Dockerfile
  context: .

spec:
  operator: xgboost
  image: image
  command: "python3 -u main.py --operator=xgboost --sleep=300 --tb-write=True"

  #Optional
  # storage:
  #   sharedVolume:
  #     mountPoint: "/mnt/shared"
  #     sizeGB: 16
  #     storageClass: longhorn-xfs
  #     accessMode: string  # ReadWriteOnce / ReadWriteOncePod / ReadOnlyMany / ReadWriteMany

  tensorboard:
    enabled: true

  types:
    Master:
      count: 1
      resources:
        cpus: 1
        ramRatio: 2
        shmSizeGB: 0
    Worker:
      count: 1
      resources:
        cpus: 1
        ramRatio: 2
        shmSizeGB: 0

