kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  context: smoke-test # smoke-test folder
  dockerfile: ./build/Dockerfile

spec:
  operator: jobset
  image: image
  command: "python3 -u main.py --operator=jobset --sleep=300 --tb-write=True"

  tensorboard:
    enabled: true

  types:
    master:
      count: 1
      resources:
        cpus: 1
        ramRatio: 2
        shmSizeGB: 0
    worker:
      count: 1
      resources:
        cpus: 1
        ramRatio: 2
        shmSizeGB: 0

