AICHOR_AWS_ENDPOINT_URL: str = "AWS_ENDPOINT_URL"
AICHOR_INPUT_PATH: str = "AICHOR_INPUT_PATH"
AICHOR_OUTPUT_PATH: str = "AICHOR_OUTPUT_PATH"
AICHOR_OUTPUT_BUCKET_NAME: str = "AICHOR_OUTPUT_BUCKET_NAME"
AICHOR_TENSORBOARD_PATH: str = "AICHOR_LOGS_PATH"

HF_TOKEN: str = "HF_TOKEN"